const cities = [
    { city: "Tokyo", country: "Japan" },
    { city: "Delhi", country: "India" },
    { city: "Shanghai", country: "China" },
    { city: "São Paulo", country: "Brazil" },
    { city: "Mumbai", country: "India" },
    { city: "Cairo", country: "Egypt" },
    { city: "Dhaka", country: "Bangladesh" },
    { city: "Mexico City", country: "Mexico" },
    { city: "Beijing", country: "China" },
    { city: "Osaka", country: "Japan" },
    { city: "New York City", country: "USA" },
    { city: "Karachi", country: "Pakistan" },
    { city: "Chongqing", country: "China" },
    { city: "Istanbul", country: "Turkey" },
    { city: "Buenos Aires", country: "Argentina" },
    { city: "Kolkata", country: "India" },
    { city: "Kinshasa", country: "Democratic Republic of the Congo" },
    { city: "Lagos", country: "Nigeria" },
    { city: "Rio de Janeiro", country: "Brazil" },
    { city: "Tianjin", country: "China" },
    { city: "Guangzhou", country: "China" },
    { city: "Chennai", country: "India" },
    { city: "Bogotá", country: "Colombia" },
    { city: "Chennai", country: "India" },
    { city: "Paris", country: "France" },
    { city: "Lima", country: "Peru" },
    { city: "Bangkok", country: "Thailand" },
    { city: "Los Angeles", country: "USA" },
    { city: "Columbus", country: "USA" },
    { city: "Wuhan", country: "China" },
    { city: "Hangzhou", country: "China" },
    { city: "Hyderabad", country: "India" },
    { city: "Nairobi", country: "Kenya" },
    { city: "Berlin", country: "Germany" },
    { city: "Madrid", country: "Spain" },
    { city: "Toronto", country: "Canada" },
    { city: "Santiago", country: "Chile" },
    { city: "Alexandria", country: "Egypt" },
    { city: "Riyadh", country: "Saudi Arabia" },
    { city: "Hanoi", country: "Vietnam" },
    { city: "Barcelona", country: "Spain" },
    { city: "Bangalore", country: "India" },
    { city: "Melbourne", country: "Australia" },
    { city: "Athens", country: "Greece" },
    { city: "Lisbon", country: "Portugal" },
    { city: "Virginia Beach", country: "USA" },
    { city: "Medellín", country: "Colombia" },
    { city: "Addis Ababa", country: "Ethiopia" },
    { city: "Belo Horizonte", country: "Brazil" },
    { city: "Cape Town", country: "South Africa" },
    { city: "Kuala Lumpur", country: "Malaysia" },
    { city: "Abidjan", country: "Ivory Coast" },
    { city: "Algiers", country: "Algeria" },
    { city: "Stockholm", country: "Sweden" },
    { city: "Manila", country: "Philippines" },
    { city: "Pune", country: "India" },
    { city: "San Francisco", country: "USA" },
    { city: "Brisbane", country: "Australia" },
    { city: "Frankfurt", country: "Germany" },
    { city: "Montreal", country: "Canada" },
    { city: "Sofia", country: "Bulgaria" },
    { city: "Düsseldorf", country: "Germany" },
    { city: "Helsinki", country: "Finland" },
    { city: "Copenhagen", country: "Denmark" },
    { city: "Vienna", country: "Austria" },
    { city: "Bucharest", country: "Romania" },
    { city: "Nairobi", country: "Kenya" },
    { city: "Bamako", country: "Mali" },
    { city: "Tunis", country: "Tunisia" },
    { city: "Brussels", country: "Belgium" },
    { city: "Vilnius", country: "Lithuania" },
    { city: "Oslo", country: "Norway" },
    { city: "Tallinn", country: "Estonia" },
    { city: "Zagreb", country: "Croatia" },
    { city: "Catania", country: "Italy" },
    { city: "Sofia", country: "Bulgaria" },
    { city: "Sarajevo", country: "Bosnia and Herzegovina" },
    { city: "Podgorica", country: "Montenegro" },
    { city: "Tbilisi", country: "Georgia" },
    { city: "Yerevan", country: "Armenia" },
    { city: "Tashkent", country: "Uzbekistan" },
    { city: "Nassau", country: "Bahamas" },
    { city: "Helsinki", country: "Finland" },
    { city: "Riga", country: "Latvia" },
    { city: "Amsterdam", country: "Netherlands" },
    { city: "Luxembourg City", country: "Luxembourg" },
    { city: "Chisinau", country: "Moldova" },
    { city: "Kyiv", country: "Ukraine" },
    { city: "Tirana", country: "Albania" },
    { city: "Baku", country: "Azerbaijan" },
    { city: "Lviv", country: "Ukraine" },
    { city: "Prague", country: "Czech Republic" },
    { city: "Budapest", country: "Hungary" },
    { city: "Bratislava", country: "Slovakia" },
    { city: "Vilnius", country: "Lithuania" },
    { city: "Banja Luka", country: "Bosnia and Herzegovina" },
    { city: "Gibraltar", country: "Gibraltar" },
    { city: "Porto", country: "Portugal" },
    { city: "Milan", country: "Italy" },
    { city: "Palermo", country: "Italy" },
    { city: "Naples", country: "Italy" },
    { city: "Florence", country: "Italy" },
    { city: "Geneva", country: "Switzerland" },
    { city: "Lausanne", country: "Switzerland" },
    { city: "Basel", country: "Switzerland" },
    { city: "Zurich", country: "Switzerland" },
    { city: "San Diego", country: "USA" },
    { city: "Seattle", country: "USA" },
    { city: "Dallas", country: "USA" },
    { city: "Atlanta", country: "USA" },
    { city: "Charlotte", country: "USA" },
    { city: "Phoenix", country: "USA" },
    { city: "Jacksonville", country: "USA" },
    { city: "Indianapolis", country: "USA" },
    { city: "San Antonio", country: "USA" },
    { city: "Boston", country: "USA" },
    { city: "Washington, D.C.", country: "USA" },
    { city: "Houston", country: "USA" },
    { city: "Detroit", country: "USA" },
    { city: "Philadelphia", country: "USA" },
    { city: "Baltimore", country: "USA" },
    { city: "Minneapolis", country: "USA" },
    { city: "Orlando", country: "USA" },
    { city: "Tampa", country: "USA" },
    { city: "Miami", country: "USA" },
    { city: "Cleveland", country: "USA" },
    { city: "Cincinnati", country: "USA" },
    { city: "Kansas City", country: "USA" },
    { city: "St. Louis", country: "USA" },
    { city: "Milwaukee", country: "USA" },
    { city: "Portland", country: "USA" },
    { city: "Sacramento", country: "USA" },
    { city: "Columbus", country: "USA" },
    { city: "Virginia Beach", country: "USA" },
    { city: "Las Vegas", country: "USA" },
    { city: "Omaha", country: "USA" },
  ];
  
  console.log(cities.length)